version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.4
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec appraisal install
      - run: bundle exec appraisal rake test
